GET http://localhost:3003/api/blogs
###
DELETE http://localhost:3003/api/blogs/64b920b9f698155476aa7592
Authorization: Bearer 
###
PUT http://localhost:3003/api/blogs/648b775d21780044d54a7c93
content-type: application/json

{
  "likes": 9000
}
###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer 
{
  "title": "The Last Dance",
  "author": "Michael Jordan",
  "url": "www.jordangoat.com/the-last-dance"
}
###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "murillow",
  "name": "Murillo Bazilio",
  "password": "123qwe123"
}
###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username" : "murillow",
  "password" : "123qwe123"
}
